name: 'DynamoDB Actions'
description: 'GitHub action that integrates with Amazon DynamoDB'
author: 'MooYeol Prescott Lee'
inputs:
  operation:
    description: 'Operation Type (e.g. get, put, delete)'
    required: true
  region:
    description: 'AWS Region'
    required: true
  table:
    description: 'Target Table Name or ARN'
    required: true
  key:
    description: 'Item Key'
    required: false
  item:
    description: 'Item Value, Only required for put operation'
    required: false
  consistent:
    description: 'Enable consistent read'
    required: false
outputs:
  item:
    description: 'JSON-serialized Item'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'database'
  color: 'blue'
